### ISSUE TITLE
'UnsupportedOperationException' when passing immutable Map as options to 'createPhraseNode'

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1221]
Passing a map created with `Map.of` as in example below causes error:

```
java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:1072)
	at org.asciidoctor.jruby.extension.internal.JRubyProcessor.createPhraseNode(JRubyProcessor.java:200)
	at org.asciidoctor.extension.BaseProcessor.createPhraseNode(BaseProcessor.java:109)
	at org.asciidoctor.maven.test.processors.ManpageInlineMacroProcessor.process(ManpageInlineMacroProcessor.java:20)
	at org.asciidoctor.maven.test.processors.ManpageInlineMacroProcessor.process(ManpageInlineMacroProcessor.java:8)
	at org.asciidoctor.jruby.extension.processorproxies.InlineMacroProcessorProxy.process(InlineMacroProcessorProxy.java:123)
```

```java
public class ManpageInlineMacroProcessor extends InlineMacroProcessor {

    public ManpageInlineMacroProcessor(String macroName) {
        super(macroName);
    }

    @Override
    public String process(ContentNode parent, String target, Map<String, Object> attributes) {

        final Map<String, Object> options = Map.of(
                "type", ":link",
                "target", target + ".html");
        return createPhraseNode(parent, "anchor", target, attributes, options).convert();
    }

}
```

I see the code modifies the user input map https://github.com/asciidoctor/asciidoctorj/blob/e2994e0395bd002e0736ee6a25b452d9149825e2/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/extension/internal/JRubyProcessor.java#L203. I don't think we should be modifying user input but creating a copy for:
* Safety: the user may be doing something else with the Map.
* Java support: immutable constructors should be supported, I don't see a reason why we should not.

There might be other similar cases with other user input :thinking:

**Comment by robertpanzer** [comment]
Agree, we should create a copy of the map.
