### ISSUE TITLE
Rendering a file fails if it is located at the root of the filesystem, e.g. /foo.adoc

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#284]
When a file should be rendered given an absolute path in the root of the filesystem rendering fails with this exception:

```
java.lang.IllegalArgumentException: Directory does not exist: 
	at org.asciidoctor.GlobDirectoryWalker.checkInput(GlobDirectoryWalker.java:97)
	at org.asciidoctor.GlobDirectoryWalker.<init>(GlobDirectoryWalker.java:36)
	at 
```

This is due to an error in my latest PR to allow rendering files defined via absolute paths.
The problem is a classical off-by-1 problem: The last '/' of the path is omitted and therefore the path is empty in case of the root directory.

**Comment by robertpanzer** [comment]
Fixed on master with https://github.com/asciidoctor/asciidoctorj/commit/e101b4bcfba922050b8bd38348d6510cea7f432c
Fixed on asciidoctorj-1.6.0 with https://github.com/asciidoctor/asciidoctorj/commit/bb5c645050ddd2d465b54e1364b5664e4002d89d
