### ISSUE TITLE
Asciidoctorj-1.6.0 Definition lists: Don't know what to do with a Array

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctorj#404]
Set up a document that contains a definition list.

```
= Title

== Chapter

first term:: definition of first term
section term:: definition of second term
```

This stack trace pops up

```
Don't know what to do with a Array
java.lang.IllegalArgumentException: Don't know what to do with a Array
	at org.asciidoctor.ast.NodeConverter$NodeType.getNodeType(NodeConverter.java:69)
	at org.asciidoctor.ast.NodeConverter.createASTNode(NodeConverter.java:97)
	at org.asciidoctor.internal.RubyBlockListDecorator.get(RubyBlockListDecorator.java:84)
	at org.asciidoctor.internal.RubyBlockListDecorator.get(RubyBlockListDecorator.java:14)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
```

The problem seems to be access to `ListImpl.getItems()`. 

This happily works for ther kinds of lists, but not for definition lists.

**Comment by mojavelinux** [comment]
This is because definition lists are...special :) Each item in the definition list is an array. The first item is a collection of terms, each a ListItem. The second item is the item itself, also a ListItem.

In other words:

```
item = [[term1, term2, ...], item]
```

This is a great opportunity to map to a strongly typed model in AsciidoctorJ.

We should use the terminology recommended in the HTML5 spec.

**Comment by ysb33r** [comment]
Having looked at the code I see it is emitted from this block of code in NodeConverter.

```java
        public static NodeType getNodeType(RubyClass rubyClass) {
            Ruby runtime = rubyClass.getRuntime();
            for (NodeType nodeType: values()) {
                if (nodeType.getRubyClass(runtime).equals(rubyClass)) {
                    return nodeType;
                }
            }
            throw new IllegalArgumentException("Don't know what to do with a " + rubyClass);
        }
```

**Comment by ysb33r** [comment]
@mojavelinux How is this mapped in terms of your statement above?
```
first term:: definition of first term
section term:: definition of second term
```

**Comment by mojavelinux** [comment]
...keep in mind I'm not saying that this will work in AsciidoctorJ, just that I see where it is likely getting confused.

```
[
  [[ListItem("first term")], [ListItem("definition of first term")],
  [[ListItem("second term")], [ListItem("definition of second term")],
]
```

The outer array is "items". Each item is an array. Each term is an array.

**Comment by mojavelinux** [comment]
You can see the traversal here: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L501-L514

It wasn't designed really to be a public API. It's designed more as an internal AST representation (hence the array of array of array).

**Comment by robertpanzer** [comment]
@mojavelinux Do you think this is likely to change in Asciidoctor 1.6.0, so that such an item could get an own class? 
Or will it stay like this? This would mean that I would have to add some kind of heuristics to recognize a DefinitionList.

**Comment by mojavelinux** [comment]
That's a very good question. I suppose we could change it for 1.6.0. Perhaps file an issue. You can tell the list type of checking the context (`:dlist`). But that's still a bit flimsy.

**Comment by ysb33r** [comment]
I got excited, but then realised that you have not merged this yet.

**Comment by robertpanzer** [comment]
I can barely remember what happened to this.
I think I skipped it in favor of waiting for own node types for definition lists.
The recognition of definition list items is a bit flaky, as it checks for a certain array structure.

Apparently I forgot to file an issue for core. :-)

**Comment by robertpanzer** [comment]
But I see that it could make sense to merge it now and fix it again once we have a change in core to get you going forward again.

**Comment by robertpanzer** [comment]
@ysb33r Are you sure that it's still not working for you? Definition Lists (or more exactly DescriptionLists) should be already part of the 1.6.0 branch: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core/src/test/groovy/org/asciidoctor/WhenADocumentContainsADefinitionList.groovy

**Comment by ysb33r** [comment]
I  just refreshed the dependencies - Taking the snapshot from Artifactory. This is the full stacktrace I'm getting(Notice the `gems/asciidoctor-1.5.4`):

```
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `convert' for #<Array:0x657c62b8>
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:526)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.leanpub.internal.LeanpubSpecification.generateOutput(LeanpubSpecification.groovy:60)
	at org.asciidoctor.leanpub.LabeledListsSpec.Labeled lists should process examples form Asciidoctor user guide(LabeledListsSpec.groovy:23)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `convert' for #<Array:0x657c62b8>
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/list.rb:30)
	at RUBY.block in content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2300)
	at RUBY.content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71)
	at RUBY.block in content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2300)
	at RUBY.content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
```

The test doc is this:

```
= Labeled lists
Asciidoctor Team <foo@bar.example>

[chapter]
== Single line

first term:: definition of first term
section term:: definition of second term

[chapter]
== Multi-line

first term::
definition of first term
on two lines
section term::
definition of second term
can be on multiple lines

[chapter]
== Q & A

[qanda]
What is Asciidoctor?::
  An implementation of the AsciiDoc processor in Ruby.
What is the answer to the Ultimate Question?:: 42

[chapter]
== Mixed

Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace
```

**Comment by ysb33r** [comment]
Found the problem. I did not realise it was now represented as `DescriptionList`.

**Comment by ysb33r** [comment]
I have found anotehr issue, but I think it is actually in core Asciidoctor - will raise it there. However, I am closing this now as I can confirm the standard functionality is working.
