### ISSUE TITLE
Registering a postprocessor class fails

### ISSUE THREAD

**Issue by sclassen** [asciidoctor/asciidoctorj#451]
The following will fail

```java
public class MyExtensionRegistry implements ExtensionRegistry {
    void register(Asciidoctor asciidoctor) {
        asciidoctor.javaExtensionRegistry().postprocessor(MyPostProcessor.class)
    }
}

public class MyPostProcessor extends Postprocessor {
    @Override
    String process(Document document, String output) {
        return output
    }
}
```

if you register an instance of MyPostProcessor instead of the class everything works fine.

**Comment by mojavelinux** [comment]
This problem was recently resolved (and I think resolved in 1.6.0 as well). The problem is that JRuby only recognized raw class names that have a certain package prefix. The workaround is to give it a package prefix like "org.yada" or "com.yada". The fix that was applied is to properly escape the class name so that JRuby knows it is a class.

See #443.

**Comment by sclassen** [comment]
The exception is the following:

```


org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - wrong number of arguments (1 for 0)
	at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:314)
	at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:422)
	at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:524)
	at org.asciidoctor.extension.GebBlockTest.test keys in geb block(GebBlockTest.groovy:67)
Caused by: org.jruby.exceptions.RaiseException: (ArgumentError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - wrong number of arguments (1 for 0)
	at RUBY.add_document_processor(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/extensions.rb:1140)
	at RUBY.postprocessor(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/extensions.rb:690)
	at RUBY.postprocessor(<script>:45)
	at org.jruby.RubyBasicObject.instance_exec(org/jruby/RubyBasicObject.java:1603)
	at RUBY.activate(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/extensions.rb:539)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.activate(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/extensions.rb:534)
	at RUBY.initialize(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:438)
	at RUBY.load(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1344)
	at RUBY.convert(/home/scl/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4/fff9a4fe8f098a2b3a64d87988e685883a5bb5d0/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
	at RUBY.convert(<script>:72)
	at org.jruby.gen.InterfaceImpl667824891.convert(org/jruby/gen/InterfaceImpl667824891.gen:13)
	... 1 more
```

**Comment by sclassen** [comment]
registering BlockProcessor and BlockMacroProcessor with passing the class and not an instance works

**Comment by mojavelinux** [comment]
Oops, my mistake. This is something different. I think the problem is that you must implement the constructor right now in your extension class or else you get this failure.

See https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/test/java/org/asciidoctor/extension/ArrowsAndBoxesIncludesPostProcessor.java

**Comment by sclassen** [comment]
Thank you. I can confirm that the following constructor solves the problem:

```java
    public MyPostProcessor(DocumentRuby documentRuby) {
        super()
    }
```

**Comment by robertpanzer** [comment]
Passing in a processor instance should not require any specific constructor at all,
Either a no-arg or a constructor taking a constructor taking a options map should be required.

**Comment by robertpanzer** [comment]
This comment only applies to 1.6.0, forgot this in my comment, too late for me after being 27 hours awake ;-)

**Comment by robertpanzer** [comment]
@sclassen Do you think we can close this issue?

**Comment by sclassen** [comment]
yes I do think so. Maybe you want to think about a better error message or some kind of check to tell the user which constructor is expected for a xxxProcessor.
