### ISSUE TITLE
TreeParser w/ asciidoctorj-pdf leads to "cannot convert instance" Exception

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctorj#459]
The following test breaks if (and only if) I call document.getBlocks() in the Treeparser **and** create a PDF. I'm running asciidoctorj-1.5.4 and asciidoctorj-pdf-1.5.0-alpha.11. 

The sample code is available here: https://github.com/ahus1/asciidoctor-extensions

The exception is not helpful to me. I'm looking for a workaround or fix.

A simple TreeParser:

```
public class UrlHyphenationProcessor extends Treeprocessor {

    public UrlHyphenationProcessor(Map<String, Object> config) {
        super(config);
    }

    @Override
    public Document process(Document document) {

        // this breaks PDF creation!
        final List<AbstractBlock> blocks = document.getBlocks();

        return document;
    }

}
```

and then render a document **as PDF**

```
public class UrlHyphenationProcessorTest {

    @Test
    public void processFile() {
        File inputFile = getResource("sample.adoc");
        File outputFile = new File(inputFile.getParentFile(), "sample.pdf");
        outputFile.delete();
        Asciidoctor.Factory.create().convertFile(inputFile,
            options().backend("pdf").get());
        assertThat(outputFile).exists();
    }

    /* ... */

}
```

this leads to an exception like this: 

```
(TypeError) cannot convert instance of class org.jruby.RubyObject to class java.lang.String

org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (TypeError) cannot convert instance of class org.jruby.RubyObject to class java.lang.String

	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:434)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:554)
	at UrlHyphenationProcessorTest.processFile(UrlHyphenationProcessorTest.java:26)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) cannot convert instance of class org.jruby.RubyObject to class java.lang.String
	at org.jruby.gen.InterfaceImpl186069675.convert(org/jruby/gen/InterfaceImpl186069675.gen:13)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104)
	at RUBY.content(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104)
	at RUBY.convert_content_for_block(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112)
	at RUBY.convert_content_for_block(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112)
	at RUBY.convert_document(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:163)
	at RUBY.convert_document(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:163)
	at RUBY.convert(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96)
	at RUBY.convert(.../asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96)
	at RUBY.convert(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert_file(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convert_file(.../asciidoctorj/1.5.4/asciidoctorj-1.5.4.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl35397794.convertFile(org/jruby/gen/InterfaceImpl35397794.gen:13)
```

**Comment by robertpanzer** [comment]
Hi Alex,

This should be resolved on the 1.6.0 branch and is one of the reasons we
rewrote the whole AST and Processor layer.

Would be great if you could retest with a current 1.6.0 Snapshot or the
alpha.1.

Cheers
Robert

Am Samstag, 7. Mai 2016 schrieb Alexander Schwartz :

**Comment by ahus1** [comment]
I checked out the branch asciidoctorj-1.6.0 and used gradlew to build a SNAPSHOT. The error is gone, I'll continue my journey. 

Would it be a workaround to write a ruby extension instead if I want it to be working with asciidoctorj-1.5.x? I haven't tried it yet because my Ruby skills are non-existent.

**Comment by mojavelinux** [comment]
@ahus1 The rule of thumb right now is that if you are writing an extension in Java, you should be using AsciidoctorJ 1.6.0 alpha or snapshot (which uses Asciidoctor 1.5.4 underneath atm). If, for some reason, you can't use AsciidoctorJ 1.6.0, then it's safer and more efficient to write the extension in Ruby.

We learned a lot about the needs of extension writers in AsciidoctorJ 1.5.x. 1.6.0 incorporates the redesign to address those needs. If I were writing extensions, I would only be looking to the future, which is AsciidoctorJ 1.6.0. We're going to do our best to get it out over the summer.

**Comment by ahus1** [comment]
1.6.0 snapshot works better. Thanks.

**Comment by AlexanderZobkov** [comment]
Hello @robertpanzer and @mojavelinux ,

It looks like AsciidoctorJ 1.6.0 is not compatible with asciidoctor-maven-plugin 1.5.3.
Is it possible to use an extension in Ruby when using asciidoctor-maven-plugin?

**Comment by robertpanzer** [comment]
Hi Alexander,

Yes, you're right. The released version of the asciidoctor-maven-plugin is not compatible with the 1.6.0 versions of Asciidoctorj. 
When using a alpha or snapshot version of AsciidoctorJ 1.6.0 it's best to also use a snapshot of the asciidoctor-maven-plugin. 

We're trying to keep the plugin compatible while cleaning up the API of AsciidoctorJ. 

Cheers
Robert

**Comment by AlexanderZobkov** [comment]
Hello Robert,

Thanks, I have one more question. Probably it's out scope of this particullar issue, please let me know if I need to create an additional issue.

Is it possible to pass some configuration parameters to TreeProcessor from outside? There is a constructor that accepts Map<String, Object> config
```
    public Treeprocessor(Map<String, Object> config) {
        super(config);
    }
```
However based on sources It looks like it's not functioning for configuration. 
As far as I can see from Ruby based extensions, the only way to pass some configuration parameters is pass special asciidoctor attributes that should be honored/interpreted by a particular extension.

**Comment by robertpanzer** [comment]
Hi Alexander,

there are generally three ways in AsciidoctorJ to configure a Java extension:

1. You register an instance of a processor at the JavaExtensionRegistry. Before registering the Processor ensure that all options are set on the Processor.config map.
2. You register a class and ensure that the Processor.config is filled appropriately in the constructor.
3. You use the annotations to configure your Processor like @Name, @ContentModel, @Contexts etc. https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/docs/integrator-guide.adoc should describe what annotations make sense for what extension types. 

Actually for TreeProcessors there are no useful config options that I am aware of.

There is no means to configure a Ruby extension from AsciidoctorJ besides defining the name for a Block Macro, Inline Macro or Blockprocessor.

Hope that response matches your questions ;-)

Cheers
Robert

**Comment by mojavelinux** [comment]
> As far as I can see from Ruby based extensions, the only way to pass some configuration parameters is pass special asciidoctor attributes that should be honored/interpreted by a particular extension.

This is generally the approach that we've followed with other extensions. I would be open to finding a way to pass option via the API. I just wanted to let you know that your instinct to use designated attributes is consistent with what we've done elsewhere.
