### ISSUE TITLE
PDF generation does not work with AsciidoctorJ 1.6.0-alpha.3 on Windows

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#471]
PDF generation does not work on Win10 with the latest alpha release 1.6.0-alpha.3 of AsciidoctorJ using JRuby 9.1.2.0.

You will get this error:
```
c:\Temp\asciidoctorj-1.6.0-alpha.3\bin>asciidoctorj -b pdf c:\temp\test.adoc
Exception in thread "main" org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error 123 - FindFirstFile
        at RUBY.symlink?(uri:classloader:/jruby/kernel/file.rb:127)
        at RUBY.<module:Prawn>(uri:classloader:/gems/prawn-1.3.0/lib/prawn.rb:15)
        at RUBY.<top>(uri:classloader:/gems/prawn-1.3.0/lib/prawn.rb:11)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.(root)(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:3)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.require_relative(uri:classloader:/jruby/kernel/kernel.rb:13)
        at RUBY.<top>(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf.rb:3)
```

Just opened this issue for AsciidoctorJ to have a relation to https://github.com/jruby/jruby/issues/3957

**Comment by mattadamson** [comment]
Hi

Is there a known combination which will work even if not the latest version of any of the referenced components? The current combination I'm trying resulting in the same error is

					<dependency>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctorj-pdf</artifactId>
						<version>1.5.0-alpha.11</version>
					</dependency>
					<dependency>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctorj</artifactId>
						<version>1.6.0-alpha.3</version>
					</dependency>
					<dependency>
						<groupId>org.jruby</groupId>
						<artifactId>jruby-complete</artifactId>
						<version>1.7.24</version>
					</dependency>



Caused by: org.apache.maven.plugin.PluginExecutionException: Execution output-pd
f of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.4-SNAPSHOT:process-asciid
oc failed: (SystemCallError) Unknown error 123 - FindFirstFile
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error
123 - FindFirstFile
        at RUBY.symlink?(uri:classloader:/jruby/kernel/file.rb:127)
        at RUBY.<module:Prawn>(uri:classloader:/gems/prawn-1.3.0/lib/prawn.rb:15
)
        at RUBY.<top>(uri:classloader:/gems/prawn-1.3.0/lib/prawn.rb:11)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/ruby
gems/core_ext/kernel_require.rb:1)
        at RUBY.<top>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubyg
ems/core_ext/kernel_require.rb:55)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)

**Comment by robertpanzer** [comment]
The error indicates that you are still using JRuby 9.1.2.0.
With AsciidoctorJ 1.6.0 we're no longer using `jruby-complete` but the simple `jruby` dependency to play nicer with dependency management as `jruby-complete` contains all transitive dependencies.

So you might want to try changing to
```xml
                <dependency>
                    <groupId>org.jruby</groupId>
                    <artifactId>jruby</artifactId>
                    <version>1.7.24</version>
                </dependency>
```

**Comment by mattadamson** [comment]
thanks @robertpanzer 

so now I have

					<dependency>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctorj-pdf</artifactId>
						<version>1.5.0-alpha.11</version>
					</dependency>
					<dependency>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctorj</artifactId>
						<version>1.6.0-alpha.3</version>
					</dependency>
					<dependency>
						<groupId>org.jruby</groupId>
						<artifactId>jruby</artifactId>
						<version>1.7.24</version>
					</dependency>                


Caused by: java.lang.IllegalStateException: asciidoctor: FAILED: D:/data/swagger-doc-generator/src/docs/asciidoc/achbatchdet
ailsoperationoverview.adoc: Failed to load AsciiDoc document
        at org.asciidoctor.extension.Processor.setConfig(Processor.java:105)
        at org.asciidoctor.extension.processorproxies.BlockProcessorProxy.initia
lize(BlockProcessorProxy.java:78)
        at org.asciidoctor.extension.processorproxies.BlockProcessorProxy$INVOKE
R$i$0$1$initialize.call(BlockProcessorProxy$INVOKER$i$0$1$initialize.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMe
thod.java:671)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:356)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.
java:213)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
217)
        at org.jruby.RubyClass.newInstance(RubyClass.java:864)
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$ne
wInstance.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTw
oOrNBlock.call(JavaMethod.java:314)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:346)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
204)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.IfNode.interpret(IfNode.java:116)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.IfNode.interpret(IfNode.java:118)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:247)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:227)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:356)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.
java:213)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
217)
        at org.jruby.ast.FCallTwoArgBlockPassNode.interpret(FCallTwoArgBlockPass
Node.java:34)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:225)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:219)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:346)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
204)
        at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.jav
a:112)
        at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block
.java:206)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:19
4)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:17
7)
        at org.jruby.runtime.Block.yieldArray(Block.java:158)
        at org.jruby.RubyBasicObject.yieldUnder(RubyBasicObject.java:1649)
        at org.jruby.RubyBasicObject.instance_exec19(RubyBasicObject.java:1623)
        at org.jruby.RubyBasicObject$INVOKER$i$0$3$instance_exec19.call(RubyBasi
cObject$INVOKER$i$0$3$instance_exec19.gen)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.j
ava:202)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:316)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.
java:145)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
149)
        at org.jruby.ast.FCallNoArgBlockPassNode.interpret(FCallNoArgBlockPassNo
de.java:27)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.WhenOneArgNode.when(WhenOneArgNode.java:49)
        at org.jruby.ast.CaseNode.interpret(CaseNode.java:133)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.WhenOneArgNode.whenSlowTest(WhenOneArgNode.java:36)
        at org.jruby.ast.WhenOneArgNode.when(WhenOneArgNode.java:46)
        at org.jruby.ast.CaseNode.interpret(CaseNode.java:133)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.jav
a:112)
        at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block
.java:206)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:15
7)
        at org.jruby.runtime.Block.yield(Block.java:142)
        at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
        at org.jruby.RubyArray.each(RubyArray.java:1613)
        at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$e
ach.gen)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:316)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.
java:145)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.j
ava:154)
        at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:64
)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
170)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.IfNode.interpret(IfNode.java:116)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.IfNode.interpret(IfNode.java:118)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:247)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:227)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:356)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.
java:213)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
217)
        at org.jruby.RubyClass.newInstance(RubyClass.java:864)
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$ne
wInstance.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrTw
oOrNBlock.call(JavaMethod.java:314)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSi
te.java:346)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
204)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
        at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.IfNode.interpret(IfNode.java:118)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:225)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:219)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
202)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:225)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:219)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
202)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:225)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:219)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:
202)
        at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
        at org.jruby.ast.ReturnNode.interpret(ReturnNode.java:92)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.ja
va:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(Interpreted
Method.java:112)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.j
ava:169)
        at org.jruby.gen.InterfaceImpl1551160215.convertFile(org/jruby/gen/Inter
faceImpl1551160215.gen:13)
        at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidocto
r.java:517)
        at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidocto
r.java:498)
        at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor
.java:252)
        at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java
:321)
        at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:19
1)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:106)
        ... 20 more
Caused by: java.lang.IllegalStateException: It is only allowed to set the config
 in the constructor!

**Comment by robertpanzer** [comment]
Hi Matt,

Could you please open a new issue?
Otherwise we loose the focus of this one that PDF doesn't work with JRuby
9.1.2.0 on Win.

Cheers
Robert

Am Mittwoch, 29. Juni 2016 schrieb mattadamson :

**Comment by mattadamson** [comment]
sure we could although this error is also from windows about PDF not working and also the same dependency 1.6.0-alpha.3. I wanted to avoid a very similar "duplicate" issue. If we open a new issue what do you think is the best description?

**Comment by robertpanzer** [comment]
From the stacktrace I don’t think that this error is related to PDF.
I guess it will fail with HTML as well.

Wildly guessing I’d say that you’re registering a processor instance twice.

**Comment by madmas** [comment]
Hi, I just ran into the same problem while using 

```
   classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
   classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16'
```

 and could fix it by adding the dependency mentioned above to my gradle build:

`  classpath 'org.jruby:jruby:1.7.24' `

Thanks a lot!

**Comment by xamde** [comment]
Workaround on Windows 10 which worked for me:

```
		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj</artifactId>
			<version>1.6.0-alpha.6</version>
			<exclusions>
				<exclusion>
					<groupId>org.jruby</groupId>
					<artifactId>jruby</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jruby</groupId>
					<artifactId>jruby-complete</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.asciidoctor</groupId>
			<artifactId>asciidoctorj-pdf</artifactId>
			<version>1.5.0-alpha.16</version>
			<exclusions>
				<exclusion>
					<groupId>org.jruby</groupId>
					<artifactId>jruby</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jruby</groupId>
					<artifactId>jruby-complete</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.jruby</groupId>
			<artifactId>jruby</artifactId>
			<version>9.1.16.0</version>
		</dependency>
```

**Comment by dariahervieux** [comment]
I had the same issue for gradle build (4.7).
Solved by:
```
buildscript {
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.7'
        classpath ('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16')  {
                    exclude group: 'org.jruby'
        }
        classpath 'org.jruby:jruby:9.1.17.0'
    }
}
```
