### ISSUE TITLE
Using a Processor makes rendering documents with a TOC fail

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#497]
As first observed in asciidoctor/asciidoctor-maven-plugin#258 when using a Processor that iterates over the blocks of a document, rendering that Document with a table of contents will fail.

That means with this Processor:
```java
public class MyTreeprocessor extends Treeprocessor {
    public TerminalCommandTreeprocessor(Map<String, Object> config) {
        super(config);
    }

    @Override
    public Document process(Document document) {
        final List<AbstractBlock> blocks = this.document.blocks();
        return document;
    }
```
this code will fail:
```java
        JavaExtensionRegistry javaExtensionRegistry = this.asciidoctor.javaExtensionRegistry();
        javaExtensionRegistry.treeprocessor(MyTreeprocessor.class);
        String content = asciidoctor.renderFile(
            classpath.getResource("sample-with-sections.ad"),
            options().toFile(false)
                .attributes(AttributesBuilder.attributes().tableOfContents(true))
                .get());
```

The exception is this:
```
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `level' for nil:NilClass
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:434)
	at org.asciidoctor.extension.WhenJavaExtensionIsRegistered.when_using_a_tree_processor_a_toc_should_still_be_created(WhenJavaExtensionIsRegistered.java:401)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.asciidoctor.util.ClasspathResources$1.evaluate(ClasspathResources.java:24)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `level' for nil:NilClass
	at RUBY.outline(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/html5.rb:300)
	at RUBY.embedded(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/html5.rb:272)
	at RUBY.convert(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/base.rb:34)
	at RUBY.convert(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert_file(/Users/robertpanzer/dev/asciidoctorj/asciidoctorj-core/build/resources/main/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl1854727011.convertFile(org/jruby/gen/InterfaceImpl1854727011.gen:13)
```

**Comment by robertpanzer** [comment]
This error affects AsciidoctorJ 1.5.4.1. 1.5.3.2 and earlier are not affected.

**Comment by mojavelinux** [comment]
> This error affects AsciidoctorJ 1.5.4.1. 1.5.3.2 and earlier are not affected.

Actually, it's more accurate to say that all versions of AsciidoctorJ 1.5.x are affected (the context values are converted from a Symbol to a String). It's just that this change doesn't cause a problem with this scenario until 1.5.4.1 because the outline method started relying on the context value.

**Comment by AlexanderZobkov** [comment]
Hello Robert,

It looks like I observe a similar issue, is this fix covers the following issue as well?

```
testSpellChecking(com.xxxxxx.ascidoctorj.spellchecker.SpellCheckingTreeprocessorTest)  Time elapsed: 8.126 sec  <<< ERROR!
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `blocks?' for #<Java::OrgAsciidoctorAst::ListItemImpl:0x196624bf>
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:434)
	at com.xxxxxx.ascidoctorj.spellchecker.SpellCheckingTreeprocessorTest.testSpellChecking(SpellCheckingTreeprocessorTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	...
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `blocks?' for #<Java::OrgAsciidoctorAst::ListItemImpl:0x196624bf>
	at RUBY.ulist(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/docbook5.rb:479)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.ulist(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/docbook5.rb:471)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/base.rb:34)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/list.rb:30)
	at org.jruby.gen.InterfaceImpl350798719.convert(org/jruby/gen/InterfaceImpl350798719.gen:13)
	at RUBY.content(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.section(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/docbook5.rb:63)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/base.rb:34)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:71)
	at org.jruby.gen.InterfaceImpl1208446731.convert(org/jruby/gen/InterfaceImpl1208446731.gen:13)
	at RUBY.content(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104)
	at RUBY.document(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/docbook5.rb:33)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/converter/base.rb:34)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert_file(/home/user/.rvm/gems/ruby-2.2.1/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl1424012009.convertFile(org/jruby/gen/InterfaceImpl1424012009.gen:13)`
```

**Comment by robertpanzer** [comment]
Hi Alexander,

this is not fixed yet.
Just reproduced it.
Would be great if you could file a separate issue.

Cheers
Robert

**Comment by robertpanzer** [comment]
Good thing is, that I already reproduced this error and can fix it.
