### ISSUE TITLE
Exception when retrieving blocks in a Treeprocessor with PDF backend

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#511]
The following case does not fail when using "html5" backend, using v1.5.4.1.

When rendering a document with the following code:
```
public static void main(String[] args) {
        Asciidoctor asciidoctor = Asciidoctor.Factory.create((String) null);

        AttributesBuilder attributes = AttributesBuilder.attributes();
        // TOC + preproc fixed in master, issue #497 
        // attributes.tableOfContents(true);
        // attributes.tableOfContents(Placement.LEFT);
        attributes.sourceHighlighter("highlightjs");

        OptionsBuilder options = OptionsBuilder.options();
        options.safe(SafeMode.UNSAFE);
        options.mkDirs(true);
        options.attributes(attributes);
        //options.backend("html5");
        options.option("backend", "pdf");
        options.option("sourcemap", true);

        // Register extension
        JavaExtensionRegistry extensionRegistry = asciidoctor.javaExtensionRegistry();
        extensionRegistry.treeprocessor(TreeProcessorDemo.class);

        asciidoctor.convertFile(file("sample.adoc"), options);
    }
```

with this extension, which only retrieves the blocks of the document, no modification is done.
```
public class TreeProcessorDemo extends Treeprocessor {

    private Document document;

    public TreeProcessorDemo(Map<String, Object> config) {
        super(config);
    }

    @Override
    public Document process(Document document) {
        // Commenting this line prevents the error
        List<AbstractBlock> blocks = document.blocks();
        return document;
    }

}
```

I get this error
```
Exception in thread "main" org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (TypeError) cannot convert instance of class org.jruby.RubyObject to class java.lang.String
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:458)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:559)
	at org.asciidoctor.demos.AsciidoctorExtensionRunner.main(AsciidoctorExtensionRunner.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) cannot convert instance of class org.jruby.RubyObject to class java.lang.String
	at org.jruby.gen.InterfaceImpl334666482.convert(org/jruby/gen/InterfaceImpl334666482.gen:13)
	at RUBY.content(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/abstract_block.rb:80)
	at RUBY.content(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1104)
	at RUBY.convert_content_for_block(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.11/cbfc984df46fe321ce884aa62f7a6fb35100ec02/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:112)
	at RUBY.convert_document(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.11/cbfc984df46fe321ce884aa62f7a6fb35100ec02/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:163)
	at RUBY.convert(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-pdf/1.5.0-alpha.11/cbfc984df46fe321ce884aa62f7a6fb35100ec02/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/asciidoctor-pdf-1.5.0.alpha.11/lib/asciidoctor-pdf/converter.rb:96)
	at RUBY.convert(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:1044)
	at RUBY.convert(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1503)
	at RUBY.convert_file(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl1741457706.convertFile(org/jruby/gen/InterfaceImpl1741457706.gen:13)
```

Here is the document I am rendering: https://github.com/abelsromero/asciidoctorj-gradle/blob/dad07b60c46041c4277dea7323a18afe2841e7f2/src/asciidoc/sample.adoc

I've confirmed that commenting the line prevents the error, and that the process method is executed and returns, so, the actual exception happens after it.

**Comment by abelsromero** [comment]
Not sure if related, but while printing the block attributes in the extension using the method below I 
found that some of them are not String.
The block.getAttributes() methods returns a `Map<String, Object>` according to its specification, but some are Long.

```
    public void printBlockInfo(final AbstractBlock block, final int depth) {

        String indent = new String();
        for (int i = 0; i < depth; i++) indent += " ";

        System.out.println(indent + "Name: " + block.getNodeName());

        Map<String, Object> attributes = block.getAttributes();
        for (Object attrName : attributes.keySet()) {
            System.out.println(indent + "[" +
                    attrName + " (" + attrName.getClass().getName() + ")" +
                    ": " + block.getAttributes().get(attrName) + "]");
        }

        block.getBlocks().forEach(b -> printBlockInfo(b, depth + 1));
    }
```

Here is the output
```
Name: preamble
 Name: paragraph
Name: section
 Name: paragraph
Name: section
 Name: admonition
 [style (java.lang.String): NOTE]
 [name (java.lang.String): note]
 [caption (java.lang.String): Note]
Name: section
 Name: listing
 [1 (java.lang.Long): source]
 [2 (java.lang.Long): java]
 [style (java.lang.String): source]
 [language (java.lang.String): java]
```

**Comment by mojavelinux** [comment]
I thought we had concluded that you can't use the Treeprocessor reliably with AsciidoctorJ 1.5.4. The reason it doesn't work is for all the reasons that the AsciidoctorJ 1.6.0 branch exists. That branch refactors the code to correctly map between Java and Ruby objects. My understanding is that there's no easy way to do this in AsciidcotorJ 1.5.x without replaying all the work in the 1.6.0 branch.

**Comment by mojavelinux** [comment]
In other words...your observation is exactly correct. Crazy things happen when you use a Treeprocessor to modify the AST in AsciidoctorJ 1.5.4.

**Comment by abelsromero** [comment]
Understood 👍

**Comment by mojavelinux** [comment]
@robertpanzer is my statement correct?

**Comment by mojavelinux** [comment]
(Don't always believe what I say :wink:).

**Comment by robertpanzer** [comment]
In general yes, and it has to be said that reading the nodes already
modifies them.

I just wonder if we cannot filter out these positional attributes.
I know I've already worked on that but possibly only on the 1.6.0 branch.

As I am currently enjoying the italian sun, beach & aperitifs I'll be
unable to take a look at that before next week earliest (if ist not
super-urgent)

Am Montag, 12. September 2016 schrieb Dan Allen :

**Comment by mojavelinux** [comment]
> As I am currently enjoying the italian sun, beach & aperitifs

I love to hear that. Soak up the :sun_with_face: and :cocktail:!

**Comment by robertpanzer** [comment]
Thanks, my friend!!!

Am Montag, 12. September 2016 schrieb Dan Allen :

**Comment by abelsromero** [comment]
> As I am currently enjoying the italian sun, beach & aperitifs I'll be
> unable to take a look at that before next week earliest (if ist not
> super-urgent)

Not only is not urgent for me, but I think your current matters are more important

**Comment by robertpanzer** [comment]
Just tried converting a document to PDF using a TreeProcessor that touches the document's blocks on AsciidoctorJ 1.6.0 and that worked fine.

Also tried on master and it crashed with the same error.

So yes, Treeprocessors don't play well under Asciidoctor 1.5.x.

The positional attributes should be unrelated to this.
Not sure how we can filter that, keeping the semantics that modifications to the attributes become effective.
The only solution that I can see atm would be to wrap the original map in a similar approach to what 1.6.0 does, just that in this case a RubyHash is wrapped.
But we will without any doubt hit the next limit very soon then.

(And before you ask, it's raining here today ;-) )
