### ISSUE TITLE
Exception when enabling `timings` options

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#512]
When I enable the `timings` options I get the following exception message:
```
SEVERE: (NoMethodError) undefined method `start' for true:TrueClass
Exception in thread "main" org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `start' for true:TrueClass
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:345)
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:458)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:559)
	at org.asciidoctor.demos.AsciidoctorRunner.main(AsciidoctorRunner.java:36)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `start' for true:TrueClass
	at RUBY.load(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1272)
	at RUBY.convert(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
	at RUBY.convert_file(/Users/abelsromero/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/1.5.4.1/f7ddfb2bbed2f8da3f9ad0d1a5514f04b4274a5a/asciidoctorj-1.5.4.1.jar!/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl390047945.convertFile(org/jruby/gen/InterfaceImpl390047945.gen:13)
```

It points here https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor.rb#L1272.

I tested with JRuby 1.7.26 and 9.1.0.0 without success, but I suspect the issue requires some patching in Asciidoctorj. Is that so?

**Comment by mojavelinux** [comment]
timings is not a boolean option. The purpose of that option is to pass in a timings model object which can be used to capture the timings. So you'd need to pass in an object that responded to the methods in the following class:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/timings.rb

However, at the moment I consider that option to be part of the internal API. It is used by the CLI invoker to support the commandline switch `-t`.

**Comment by abelsromero** [comment]
My confusion came from this section http://asciidoctor.org/docs/user-manual/#ruby-api-options.
Seeing how easy is to use from the ruby CLI I assumed I could just enable it from Java.

**Comment by mojavelinux** [comment]
I just noticed that error. You are correct, the documentation was misleading. I went ahead and fixed it. Now it should be clearer.

**Comment by abelsromero** [comment]
It's clear now, thanks.

PS: I checked the sources seeing the page does not update :/

Apologies for bothering, these days I have some time and went into doing some POCs.

**Comment by mojavelinux** [comment]
Our luck, updates to GitHub Pages sites are currently disabled.
