### ISSUE TITLE
`Section#number` crashes for appendix sections 

### ISSUE THREAD

**Issue by marko-bekhta** [asciidoctor/asciidoctorj#549]
`Section#number` fails with:

```
SEVERE: org.jruby.RubyException

org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (TypeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - cannot convert instance of class org.jruby.RubyString to int

	at org.asciidoctor.internal.JRubyAsciidoctor.render(JRubyAsciidoctor.java:307)
	at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:512)
	at org.hibernate.infra.asciidoctor.extensions.customnumbering.ExampleNumberingTest.charNumberingFailsTest(ExampleNumberingTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - cannot convert instance of class org.jruby.RubyString to int
	at org.jruby.gen.InterfaceImpl1251850831.number(org/jruby/gen/InterfaceImpl1251850831.gen:13)
	at org.jruby.RubyMethod.call(org/jruby/RubyMethod.java:120)
	at RUBY.parse(/Users/marko/.m2/repository/org/asciidoctor/asciidoctorj/1.5.5/asciidoctorj-1.5.5.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.parse(/Users/marko/.m2/repository/org/asciidoctor/asciidoctorj/1.5.5/asciidoctorj-1.5.5.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478)
	at RUBY.load(/Users/marko/.m2/repository/org/asciidoctor/asciidoctorj/1.5.5/asciidoctorj-1.5.5.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347)
	at RUBY.convert(/Users/marko/.m2/repository/org/asciidoctor/asciidoctorj/1.5.5/asciidoctorj-1.5.5.jar!/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465)
	at RUBY.convert(<script>:72)
	at org.jruby.gen.InterfaceImpl1900097566.convert(org/jruby/gen/InterfaceImpl1900097566.gen:13)
```

when called on appendix sections.

Here's a possible test to see the problem:

```java
public class TreeprocessorTest {

   private static Asciidoctor DOCTOR;

   @BeforeClass
   public static void initAsciidoctor() {
      DOCTOR = Asciidoctor.Factory.create();
      DOCTOR.javaExtensionRegistry().treeprocessor( CustomNumberingProcessor.class );
   }

   @Test
   public void charNumberingFailsTest() {
      DOCTOR.javaExtensionRegistry().treeprocessor( new Treeprocessor() {

         @Override public org.asciidoctor.ast.Document process(org.asciidoctor.ast.Document document) {
            Map<Integer, Section> sectionIndexMap = document.getBlocks().stream().filter( block -> block instanceof Section )
                  .map( block -> (Section) block )
                  .collect( Collectors.toMap( section -> section.numbered() ? section.number() : -1, section -> section ) );
            return document;
         }
      } );

      String content = "= Some title\n"
            + "\n"
            + ":sectnums:\n"
            + "== Some other title\n"
            + "\n"
            + "some very useful text which makes no sense.\n"
            + "\n"
            + "=== Some other inner title\n"
            + "\n"
            + "some very useful text which makes no sense.\n"
            + "\n"
            + "[appendix]\n"
            + "== Yet another title\n"
            + "\n"
            + "some very useful text which makes no sense.\n"
            + "\n"
            + "[appendix]\n"
            + "== Yet another title\n"
            + "\n"
            + "some very useful text which makes no sense.\n";
      String result = DOCTOR.convert( content, OptionsBuilder.options().safe( SafeMode.SAFE ).asMap() );
      Assert.assertNotNull( "result cannot be null", result );
      Assert.assertTrue( "converted result cannot be empty", !result.trim().isEmpty() );
   }
}
```

After looking into the problem - it seems that in Ruby `@number` can either be `fixnum` or `string`. So it seems that either adding class like `AppendixSection` (in which `AppendixSection#number` will return `String`) or somehow changing (or adding different method?) the `Section#number` is required to solve the issue.

**Comment by robertpanzer** [comment]
There are some limits with Extensions in AsciidoctorJ 1.5.x due to the way the bridge between the Ruby and the Java world is implemented.
You might want to try the latest version of the 1.6.x train which is at the moment 1.6.0-alpha.3.

**Comment by marko-bekhta** [comment]
Hi @robertpanzer,
it's needed to be a part of maven build so `asciidoctor-maven-plugin` is used. And 1.6 cannot be used there as the plugin is throwing an error:

```
Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: An API incompatibility was encountered while executing org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc: java.lang.IncompatibleClassChangeError: Found interface org.asciidoctor.ast.Document, but class was expected
```
Maybe you plan to release a compatible plugin as well ?

**Comment by robertpanzer** [comment]
Can you create an issue for the asciidoctor-maven-plugin for that?
The 1.5.5 version should already support both the current 1.5.5 as well as the latest 1.6.x of AsciidoctorJ

**Comment by abelsromero** [comment]
Hi @marko-bekhta,
I noted in your example you are marking sections as `[appendix]`, the numeration for appendixes uses letters (A, B, ...) I think that's what causing the initial problem.
`section.getNumber()` expects a number and it fails because it finds a String.
At the end, I could make the example run in a maven project with AsciidoctorJ 1.6.0-alpha.3 just removing the `[appendix]`. Using both SPI registration and pom configuration.

Btw, I did not encounter `java.lang.IncompatibleClassChangeError` in my tests, but it could be due to the fact that `org.asciidoctor.ast.Document` was a class in 1.5.5 and is an interface in 1.6.x. If you upgrade to 1.6.x (which I recommend) I guess you need to recompile the extensions as well.

**Comment by abelsromero** [comment]
I checked the Ruby core and I suspect it uses dynamic typing. `:number` uses integers until `appendix` is detected, in that case it assigns an String. This is not a major issue in Ruby due to its dynamic nature, but here  in Java...
Using reflection I could validate that for appendixes, `:number` is a string. So if you need to obtain it I fear that's not possible using the current API.

Making `getNumber()` return String seems extremely odd to me, but I don't see another way to honor the underlying API.

**Comment by marko-bekhta** [comment]
Hi @abelsromero,
thanks for the reply! My findings about `:number` were similar to yours. We are writing an extension [here](https://github.com/marko-bekhta/hibernate-asciidoctor-extensions/blob/ec497a2ad906bffa0a6ce69faf7bb764ca9c62b5/src/main/java/org/hibernate/infra/asciidoctor/extensions/customnumbering/CustomNumberingProcessor.java#L76-L84) to change the way examples are numbered. 
So this particular problem for now was solved by doing something like 
```java
	try {
		return section.numbered() ? section.number() : NOT_NUMBERED_SECTION_NUMBER;
	}
	catch (org.jruby.exceptions.RaiseException e) {
		return NOT_NUMBERED_SECTION_NUMBER;
	}
```
But I was thinking that it's worth mentioning about such issue with appendix sections numbering. 

As for the

> Making getNumber() return String seems extremely odd to me, but I don't see another way to honor the underlying API.

it really looks odd. So maybe having something like `AppendixSection` section class which extends `Section` and has a method `appendixIndex` which returns `String` might look better, while the current `number()` will return `-1` ? But i don't have a strong opinion on this though...

> Btw, I did not encounter java.lang.IncompatibleClassChangeError ...

Thanks for pointing this out. I haven't tried to recompile the extension class with 1.6 version !

**Comment by mojavelinux** [comment]
> Making getNumber() return String seems extremely odd to me, but I don't see another way to honor the underlying API.

Although it seems strange, it's actually correct. Number here means "letter number", not a mathematical number like Integer. We could introduce a type that, like BigDecimal, offers operations like increment and decrement. However, we could leave that up to the consumer.

**Comment by mojavelinux** [comment]
> So maybe having something like AppendixSection section class which extends Section and has a method appendixIndex which returns String might look better, while the current number() will return -1 ?

I could support this approach as well. It would be possible to make the return type dynamic using generics.

```java
public interface Section<N>
  N getNumber();
}

public interface Abstract extends Section<String> {
}
```

That's the most Java way to do it.

**Comment by vmj** [comment]
Hi all,

I just bumped into this issue while working on a tool that visits the AST.  Below's a failing test case that I made before finding this issue ticket (added this to my clone of `master` branch today).

```groovy
@RunWith(ArquillianSputnik)
class WhenADocumentContainsAnAppendix extends Specification {

    @ArquillianResource
    private Asciidoctor asciidoctor

    def "the section number should be 'A'"() {
        given:
        String document = '''\
            
            [appendix]
            == Some title
            '''.stripIndent()

        when:
        Document documentNode = asciidoctor.load(document, [:])

        then:
        Section appendix = documentNode.blocks[0]
        appendix.getNumber() == 'A'
    }
}
```

Since there's now no way of reaching the `A` through the AST API, should we try to fix this?  Above, there's three options suggested, as far as I can tell:

 1. Change `Section` `getNumber` to return `String`
 1. Add `AppendixSection` interface, which otherwise duplicates the `Section` interface, but returns `String` from `getNumber`
 1. Make `Section` generic, i.e. `Section<N>` with `N getNumber()`, and add two sub-interfaces for numbered and "lettered" sections

I can help with the leg work if I can.

**Comment by mojavelinux** [comment]
The number field should be a String. We've made this even more apparent in core by renaming the field from number to numeral. Although we have an internal index property to keep track of the position of the section, the numeral itself is a string representation of that position for the reader. For parts, it's a roman numeral. For regular sections, it's an arabic numeral. And for special sections, it's a letter. So String is the right common type.

See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/abstract_block.rb#L21

**Comment by robertpanzer** [comment]
@vmj it would be awesome if you want to create a PR for this. 
As @mojavelinux pointed out, we might also want to change the name to getNumeral().

**Comment by vmj** [comment]
Sounds great!  I'll start working on it later today.  Thanks to you both!
