### ISSUE TITLE
Error while generating PDF - Jenkins - asciidoc 

### ISSUE THREAD

**Issue by momo007** [asciidoctor/asciidoctorj#586]
###########################JenkinsLog##########################################

[API-Doku] $ /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven/bin/mvn -f backend/doc/pom.xml clean compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building myProject Documentation 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ doc ---
[INFO] Deleting /var/lib/jenkins/workspace/API-Doku/backend/doc/target
[INFO] 
[INFO] --- asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-api-pdf-doc) @ doc ---

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.399 s
[INFO] Finished at: 2017-10-24T13:36:35+02:00
[INFO] Final Memory: 67M/593M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc (generate-api-pdf-doc) on project doc: Execution generate-api-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2.1:process-asciidoc failed: (NotImplementedError) fstat unimplemented unsupported or native support failed to load -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

#############################################################################
---------------------------------------POM.xml-------------------------------------------------------

<modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.utiliti.myProjekt</groupId>
        <artifactId>myProjekt</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>doc</artifactId>

    <name>My Projekt Documentation</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>1.5.2.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>${asciidoctorj.pdf.version}</version>
                    </dependency>
                </dependencies>
                <configuration />

                <executions>
                    
                    <execution>
                        <id>generate-api-pdf-doc</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>process-asciidoc</goal>
                        </goals>
                        <configuration>
                            <sourceDirectory>${basedir}/api/src/main/asciidoc</sourceDirectory>
                            <sourceDocumentName>mypro-api.adoc</sourceDocumentName>
                            <backend>pdf</backend>
                            <sourceHighlighter>rouge</sourceHighlighter>
                            <attributes>
                                <icons>font</icons>
                                <pagenums/>
                                <toc/>
                                <idprefix/>
                                <idseparator>-</idseparator>
                            </attributes>
                        </configuration>
                    </execution>
                </executions>

            </plugin>
        </plugins>
        <pluginManagement>
        	<plugins>
        		
        		<plugin>
        			<groupId>org.eclipse.m2e</groupId>
        			<artifactId>lifecycle-mapping</artifactId>
        			<version>1.0.0</version>
        			<configuration>
        				<lifecycleMappingMetadata>
        					<pluginExecutions>
        						<pluginExecution>
        							<pluginExecutionFilter>
        								<groupId>
        									org.asciidoctor
        								</groupId>
        								<artifactId>
        									asciidoctor-maven-plugin
        								</artifactId>
        								<versionRange>
        									[1.5.2.1,)
        								</versionRange>
        								<goals>
        									<goal>
        										process-asciidoc
        									</goal>
        								</goals>
        							</pluginExecutionFilter>
        							<action>
        								<ignore></ignore>
        							</action>
        						</pluginExecution>
        					</pluginExecutions>
        				</lifecycleMappingMetadata>
        			</configuration>
        		</plugin>
        	</plugins>
        </pluginManagement>
    </build>

</project>

**Comment by abelsromero** [comment]
I see you are using an old version of the maven plugin. Can you try with latests version.
Here is an example :https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-example/pom.xml

Also note the example comments about the use of rouge. Honestly haven't checked with last versions, but rouge was causing problems before.

**Comment by momo007** [comment]
Hello @abelsromero 
i update the pom.xml, but the problem is still there, 


i runned the Maven with -e to see the error details:
 Command :  mvn clean compile -e

undefined method `encode' for nil:NilClass
Oct 25, 2017 11:21:12 AM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SEVERE: (NoMethodError) undefined method `encoding' for nil:NilClass
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.127 s
[INFO] Finished at: 2017-10-25T11:21:12+02:00
[INFO] Final Memory: 72M/610M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-api-pdf-doc) on project doc: Execution generate-api-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `encoding' for nil:NilClass -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (generate-api-pdf-doc) on project doc: Execution generate-api-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `encoding' for nil:NilClass
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-api-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `encoding' for nil:NilClass
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `encoding' for nil:NilClass
	at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:347)
	at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java:412)
	at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:228)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `encoding' for nil:NilClass
	at RUBY.normalize_encoding(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font/ttf.rb:174)
	at RUBY.width_of(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font_metric_cache.rb:30)
	at RUBY.width_of_string(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font.rb:276)
	at RUBY.width_of(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font.rb:143)
	at RUBY.add_fragment_to_line(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:104)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.add_fragment_to_line(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:93)
	at RUBY.apply_font_settings_and_add_fragment_to_line(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:78)
	at RUBY.apply_font_size(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:253)
	at RUBY.apply_font_settings(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:175)
	at RUBY.character_spacing(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:214)
	at RUBY.apply_font_settings(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/arranger.rb:166)
	at RUBY.apply_font_settings_and_add_fragment_to_line(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:77)
	at RUBY.wrap_line(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/line_wrap.rb:47)
	at RUBY.wrap(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/wrap.rb:53)
	at RUBY.wrap(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/formatted_text/inline_image_arranger.rb:28)
	at RUBY.render(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:226)
	at RUBY.font_size(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font.rb:101)
	at RUBY.font_size(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/prawn_ext/extensions.rb:253)
	at RUBY.render(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:219)
	at RUBY.text_rendering_mode(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-templates-0.1.1/lib/prawn/text.rb:19)
	at RUBY.render(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:214)
	at RUBY.character_spacing(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/pdf-core-0.7.0/lib/pdf/core/text.rb:214)
	at RUBY.render(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:213)
	at RUBY.save_font(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font.rb:215)
	at RUBY.render(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/text/formatted/box.rb:212)
	at RUBY.natural_content_height(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:60)
	at RUBY.with_font(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:99)
	at RUBY.save_font(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-2.2.2/lib/prawn/font.rb:215)
	at RUBY.with_font(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:92)
	at RUBY.natural_content_height(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb:58)
	at RUBY.content_height(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:336)
	at RUBY.height_ignoring_span(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:309)
	at RUBY.height(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb:317)
	at RUBY.row_heights(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table.rb:373)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.row_heights(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table.rb:369)
	at RUBY.set_row_heights(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table.rb:656)
	at RUBY.initialize(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table.rb:148)
	at RUBY.table(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/prawn-table-0.2.2/lib/prawn/table.rb:111)
	at RUBY.convert_table(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:1727)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at RUBY.convert_content_for_block(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134)
	at RUBY.convert_section(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:426)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at RUBY.convert_content_for_block(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134)
	at RUBY.convert_section(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:426)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at RUBY.convert_content_for_block(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134)
	at RUBY.convert_section(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:426)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:70)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2414)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/abstract_block.rb:79)
	at RUBY.content(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1120)
	at RUBY.convert_content_for_block(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:134)
	at RUBY.convert_document(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:207)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.16/asciidoctorj-pdf-1.5.0-alpha.16.jar!/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:118)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1060)
	at RUBY.convert(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1502)
	at RUBY.convert_file(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1201)
	at RUBY.convert_file(/var/lib/jenkins/.m2/repository/org/asciidoctor/asciidoctorj/1.5.6/asciidoctorj-1.5.6.jar!/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1575)
	at RUBY.convertFile(<script>:75)
	at org.jruby.gen.InterfaceImpl1700325588.convertFile(org/jruby/gen/InterfaceImpl1700325588.gen:13)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by abelsromero** [comment]
Found this: https://github.com/asciidoctor/asciidoctorj-pdf/issues/11

What version of jRuby do you have? btw, silly question, does this work localy outside of Jenkins?

**Comment by momo007** [comment]
i don't know (should i ask the Server admin?  with ruby -v i get nothing) , 
this works locally on my own windows ( in CMD-> with "clean compile") and as well i installed a Jenkins locally on my windows and even that can run it and generate the PDF data, but on a server (which i'm not the admin if that) i'm trying to create a job for this, and there it does not working,

**Comment by momo007** [comment]
error is solved with adding the jruby-complete dependency.
 Thank you very much for  your fast and great helps
found the solution [here](https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/164)

added to pom:
`<dependency>
                         <groupId>org.jruby</groupId>
                        <artifactId>jruby-complete</artifactId>
                        <version>9.0.4.0</version>
                    </dependency>`

**Comment by abelsromero** [comment]
Glad to hear that! :+1: 

As a reminder, you can change the version of AsciidoctorJ and jRuby (with jruby-complete) to switch your needs. Some backends required newer versions of jruby and you experiment with extensions you should use AsciidoctorJ 1.6.x.

**Comment by momo007** [comment]
thx for Hints 👍

**Comment by Sanne** [comment]
This could be closed?

**Comment by robertpanzer** [comment]
Looks like it's resolved.
If there's still a problem please reopen.
