### ISSUE TITLE
java.lang.OutOfMemoryError despite large max heap size

### ISSUE THREAD

**Issue by fapdash** [asciidoctor/asciidoctorj#787]
I've got a problem with a failing asciidoctorj build because of OutOfMemoryError.
The gradle daemon is configured to use up to 4GB of heap and the machine still has free memory when the daemon crashes.
Could it be possible that the problem is related to asciidoctorj calling JRuby and that JRuby uses the system default max heap size?

```
01:12:41.546 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 4.3 GB]
01:12:41.555 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
01:12:41.555 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=18859215-9247-4163-9863-7af0ec75d47a,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/opt/app/.gradle/daemon,pid=1554,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-Xmx4096m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]

...

Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /001_book.adoc using backend pdf
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:427)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2334)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:56)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.access$0(AsciidoctorJavaExec.groovy)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.doCall(AsciidoctorJavaExec.groovy:50)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2296)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2281)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2322)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:48)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:194)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.jruby.ext.zlib.JZlibInflate.run(JZlibInflate.java:268)
        at org.jruby.ext.zlib.JZlibInflate.internalFinish(JZlibInflate.java:315)
        at org.jruby.ext.zlib.ZStream.finish(ZStream.java:135)
        at org.jruby.ext.zlib.JZlibInflate.s_inflate(JZlibInflate.java:74)
        at org.jruby.ext.zlib.JZlibInflate$INVOKER$s$1$0$s_inflate.call(JZlibInflate$INVOKER$s$1$0$s_inflate.gen)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at uri_3a_classloader_3a_.gems.prawn_minus_2_dot_2_dot_2.lib.prawn.images.png.invokeOther87:inflate(uri:classloader:/gems/prawn-2.2.2/lib/prawn/images/png.rb:92)
        at uri_3a_classloader_3a_.gems.prawn_minus_2_dot_2_dot_2.lib.prawn.images.png.RUBY$method$initialize$0(uri:classloader:/gems/prawn-2.2.2/lib/prawn/images/png.rb:92)
        at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000840c1e840.invokeStatic(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/0x00000008405d5840.invokeExact_MT(LambdaForm$MH)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:180)
        at org.jruby.RubyClass.newInstance(RubyClass.java:990)
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:331)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at uri_3a_classloader_3a_.gems.prawn_minus_2_dot_2_dot_2.lib.prawn.images.invokeOther17:new(uri:classloader:/gems/prawn-2.2.2/lib/prawn/images.rb:92)
        at uri_3a_classloader_3a_.gems.prawn_minus_2_dot_2_dot_2.lib.prawn.images.RUBY$method$build_image_object$0(uri:classloader:/gems/prawn-2.2.2/lib/prawn/images.rb:92)
        at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000840c1a840.invokeStatic(LambdaForm$DMH)
        at java.base/java.lang.invoke.LambdaForm$MH/0x00000008405d5840.invokeExact_MT(LambdaForm$MH)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:199)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at uri_3a_classloader_3a_.gems.asciidoctor_minus_pdf_minus_1_dot_5_dot_0_dot_alpha_dot_16.lib.asciidoctor_minus_pdf.converter.invokeOther8:build_image_object(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:1131)
        at uri_3a_classloader_3a_.gems.asciidoctor_minus_pdf_minus_1_dot_5_dot_0_dot_alpha_dot_16.lib.asciidoctor_minus_pdf.converter.RUBY$block$convert_image$4(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:1131)
        at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
        at java.base/java.lang.invoke.LambdaForm$MH/0x0000000840c19840.invoke(LambdaForm$MH)
        at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
        at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)

FAILURE: Build failed with an exception.
```

**Comment by mojavelinux** [comment]
If the Gradle plugin is not passing the heap size to the process running JRuby, this is more likely an issue with the Gradle plugin. AsciidoctorJ does not use a subprocess to call JRuby. Those calls are resident within the same JVM, so it should all be the same settings. However, Gradle does use a subprocess to call AsciidoctorJ. Namely:

> Even though the DSL remains the same with this task, the internals have been changed to use the same JAVA_EXEC mechanism of the org.asciidoctor.jvm.convert plugins.

**Comment by fapdash** [comment]
Thank you! Closing then.
