### ISSUE TITLE
README instructions on publishing to local repo might be a bit off

### ISSUE THREAD

**Issue by lread** [asciidoctor/asciidoctorj#835]
## Current Behavior
Wanting to test some changes I made to asciidoctorj against another project, I followed instructions in the README to publish to my local maven repo.

I successfully started with [build the project](https://github.com/asciidoctor/asciidoctorj#build-the-project):
>```
>$ git clone https://github.com/asciidoctor/asciidoctorj
>  cd asciidoctorj
>  ./gradlew assemble
>```

Then had a bit of trouble with [publish the artifacts](https://github.com/asciidoctor/asciidoctorj#publish-the-artifacts):

> To build, assemble (but not sign) and install the archives (jars and distribution zip) into the local Maven repository, run:
>```
>$ ./gradlew -PpublishRelease=true install
>```

#### symptom
Here's the output I got:
```
> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html

FAILURE: Build failed with an exception.

* Where:
Script '/Users/lee/other-proj/asciidoctorj/gradle/sdkman.gradle' line: 4

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'sdkman_consumer_key' for project ':asciidoctorj-distribution' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
```
#### work-around
I worked around this by appending the following dummy config to my `gradle.properties`
```
sdkman_consumer_key=<some_key>
sdkman_consumer_token=<some_token>
```

#### symptom
After working around problem 1, I retried `./gradlew -PpublishRelease=true install`, this time things looked to good:
```
> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
Configuration(s) specified but the install task does not exist in project :asciidoctorj-distribution.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
13 actionable tasks: 13 up-to-date
```
But nothing got installed to my local maven repo.
#### work-around
I'm not familiar with your build so I hacked it by adding `apply plugin: 'maven'` under the `subprojects` config on [this line](https://github.com/asciidoctor/asciidoctorj/blob/d68c825273fd5768ca2f396238f600f117e3763f/build.gradle#L85).

I reran `./gradlew -PpublishRelease=true install` and got the following output:
```

> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
38 actionable tasks: 5 executed, 33 up-to-date
```
And the jars (at least the ones I needed) installed to my local maven repo:
```
$ tree ~/.m2/repository/org/asciidoctor                                                                                                                  ✔  11738  14:23:19
/Users/lee/.m2/repository/org/asciidoctor
├── asciidoctorj
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-bin.tar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-bin.zip
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
├── asciidoctorj-api
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
├── asciidoctorj-arquillian-extension
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
└── asciidoctorj-test-support
    ├── 2.1.1-SNAPSHOT
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT-javadoc.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT-sources.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT.pom
    │   └── maven-metadata-local.xml
    └── maven-metadata-local.xml

8 directories, 26 files
```
## Expected Behavior
No mods required to install jars to local maven repo.

## Action
I am probably not the best guy to fix this one, but if I am close to correct with the above, am happy to provide a PR.

**Comment by rmpestano** [comment]
Hi, for me the last workaround (apply-maven) didn't work:

```
* What went wrong:
Execution failed for task ':asciidoctorj-documentation:install'.
> Could not publish configuration 'archives'
   > Cannot publish artifact 'asciidoctorj-documentation.jar' (/Users/rpestano/projects/asciidoctorj/asciidoctorj-documentation/build/libs/asciidoctorj-documentation-2.4.1-SNAPSHOT.jar) as it does not exist.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctorj-documentation:install'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)

```

Anyone knows how to install AsciidoctorJ locally?

**Comment by rmpestano** [comment]
Actually besides the error it install in local repo, thanks @lread !

**Comment by abelsromero** [comment]
Definetly the docs are not up to date, for instance `asciidoctorj-diagram` no longer resides in this repo.

When I have needed to test local changes I run `./gradlew -Pskip.signing publishToMavenLocal` this should run the minimal steps to just install the jars locally.

**Comment by rmpestano** [comment]
Hi @abelsromero, thank you, it simply works

**Comment by lread** [comment]
Thanks @abelsromero!
