### ISSUE TITLE
NullPointerException calling containsValue() on a StructuralNode's attributes

### ISSUE THREAD

**Issue by wilkinsona** [asciidoctor/asciidoctorj#904]
I'm seeing a `NullPointerException` in a [custom `Treeprocessor`](https://github.com/spring-io/spring-asciidoctor-extensions/blob/4d4fd801e4b2dafa397f082f776c5a5285ab949c/spring-boot/spring-boot-aj2x/src/main/java/io/spring/asciidoctor/springboot/aj2x/ConfigurationPropertiesTreeprocessor.java) when [calling `containsValue("configprops")`](https://github.com/spring-io/spring-asciidoctor-extensions/blob/4d4fd801e4b2dafa397f082f776c5a5285ab949c/spring-boot/spring-boot-aj2x/src/main/java/io/spring/asciidoctor/springboot/aj2x/ConfigurationPropertiesTreeprocessor.java#L48) on the attributes of a `StructuralNode`:

```
Caused by: java.lang.NullPointerException
        at org.asciidoctor.jruby.internal.RubyAttributesMapDecorator.containsValue(RubyAttributesMapDecorator.java:41)
        at io.spring.asciidoctor.springboot.aj2x.ConfigurationPropertiesTreeprocessor.process(ConfigurationPropertiesTreeprocessor.java:48)
        at io.spring.asciidoctor.springboot.aj2x.ConfigurationPropertiesTreeprocessor.process(ConfigurationPropertiesTreeprocessor.java:54)
        at io.spring.asciidoctor.springboot.aj2x.ConfigurationPropertiesTreeprocessor.process(ConfigurationPropertiesTreeprocessor.java:54)
        at io.spring.asciidoctor.springboot.aj2x.ConfigurationPropertiesTreeprocessor.process(ConfigurationPropertiesTreeprocessor.java:54)
        at io.spring.asciidoctor.springboot.aj2x.ConfigurationPropertiesTreeprocessor.process(ConfigurationPropertiesTreeprocessor.java:43)
        at org.asciidoctor.jruby.extension.processorproxies.TreeprocessorProxy.process(TreeprocessorProxy.java:95)
        at org.asciidoctor.jruby.extension.processorproxies.TreeprocessorProxy$INVOKER$i$1$0$process.call(TreeprocessorProxy$INVOKER$i$1$0$process.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrN.call(JavaMethod.java:958)
        at org.jruby.RubyMethod.call(RubyMethod.java:120)
        at org.jruby.RubyMethod$INVOKER$i$call.call(RubyMethod$INVOKER$i$call.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroOrOneOrNBlock.call(JavaMethod.java:349)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
        at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:143)
        at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:185)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
        at org.jruby.runtime.Block.yield(Block.java:170)
        at org.jruby.RubyArray.each(RubyArray.java:1814)
        at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:537)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:141)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:191)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:178)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:191)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:178)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:203)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:325)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
        at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:143)
        at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:185)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
        at org.jruby.runtime.Block.yield(Block.java:170)
        at org.jruby.RubyIO.ensureYieldClose(RubyIO.java:1166)
        at org.jruby.RubyIO.open(RubyIO.java:1160)
        at org.jruby.RubyIO$INVOKER$s$0$0$open.call(RubyIO$INVOKER$s$0$0$open.gen)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:84)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:537)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:86)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:73)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
        at org.jruby.RubyClass.finvoke(RubyClass.java:788)
        at org.jruby.runtime.Helpers.invoke(Helpers.java:459)
        at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:377)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:390)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:366)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:85)
        ... 22 more
```

Looking at the code, it appears that `getRubyProperty("@attributes")` is returning `null` which results in `RubyAttributesMapDecorator` being created with a `null` `RubyHash`:

https://github.com/asciidoctor/asciidoctorj/blob/4f2d1105a383edc29746681559e4a52579d5041c/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/ast/impl/ContentNodeImpl.java#L86-L89

**Comment by wilkinsona** [comment]
With a work around for the above problem in place (catching the NPE and assuming that the attribute is not present), I then see a `NoMethodError` problem:

```
SEVERE: (NoMethodError) asciidoctor: FAILED: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-docs/build/docs/src/asciidoctorMultipage/asciidoc/index.htmladoc: Failed to load AsciiDoc document - undefined method `blocks' for #<Array:0x752b69e3>
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-docs/build/docs/src/asciidoctorMultipage/asciidoc/index.htmladoc using backend html5
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.call(Closure.java:421)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2368)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:80)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.access$1(AsciidoctorJavaExec.groovy)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.doCall(AsciidoctorJavaExec.groovy:72)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:67)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:49)
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-docs/build/docs/src/asciidoctorMultipage/asciidoc/index.htmladoc: Failed to load AsciiDoc document - undefined method `blocks' for #<Array:0x752b69e3>
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:400)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:366)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:85)
        ... 22 more
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: /Users/awilkinson/dev/spring-projects/spring-boot/master/spring-boot-project/spring-boot-docs/build/docs/src/asciidoctorMultipage/asciidoc/index.htmladoc: Failed to load AsciiDoc document - undefined method `blocks' for #<Array:0x752b69e3>
```

The failure is occurring when calling `getBlocks()` on a `StructuralNode`. I appear to be able to work around it with the following:

```
private List<StructuralNode> getChildren(StructuralNode structuralNode) {
	try {
		return structuralNode.getBlocks();
	}
	catch (Exception ex) {
		// Work around undefined method `blocks'
	}
	return null;
}
```

I've mentioned it here rather than in a separate issue as I am wondering if the two problems may have the same underlying cause. Please let me know if you would prefer a separate issue.

**Comment by robertpanzer** [comment]
Is it possible that you have a DescriptionList in your document?
If so it seems like getBlocks() returns the same as getItems():
https://github.com/asciidoctor/asciidoctor/blob/b075a886d599e66841cd26416c23f6fb9e0a9c92/lib/asciidoctor/list.rb#L7
And for DescriptionLists it seems to return a list of DescriptionListEntries, which are not blocks.

Until we find a solution how to make this type safe a workaround could be to not recurse into `process(StructuralNode)` when this node is a `org.asciidoctor.ast.DescriptionListEntry`.

As long as `list.items` is an alias for `list.blocks` it would probably make most sense to make DescriptionList.getBlocks()` always return an unmodifiable empty Collection.

**Comment by wilkinsona** [comment]
Thanks, @robertpanzer. That is indeed the case.

I added some rudimentary diagnostics to the two places where I'm working around the problem by catching an exception. In each case where `containsValue` or `getBlocks` fails, the associated `StructuralNode` is an instance of `org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl`:

```
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
containsValue failed when called on attributes from class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
getBlocks failed when called on class org.asciidoctor.jruby.ast.impl.DescriptionListEntryImpl
```

**Comment by robertpanzer** [comment]
Cool!
I'll try to do a fix for this asap, but that might take a bit, also thinking about the right way to do it.
Until then cutting off the recursion for DescriptionListEntries, or recursing into `DescriptionListEntry.getDescription()`, which could contain blocks again, should be a workaround that at least ...works.

**Comment by robertpanzer** [comment]
I think we missed something in the API:
Right now `StructuralNode.getBlocks()` always returns a `List<StructuralNode>`.

This doesn't seem to be true though for DescriptionLists: 
The blocks of a DescriptionList are DescriptionListEntries which **aren't** StructuralNodes.
Instead they **have** one StructuralNode for the description, and multiple StructuralNodes for each term.
In Asciidoctor Ruby a DescriptionListEntry is an Array with this structure: `[[Term 1,Term 2, ...], Description]`.

For a new major release it would probably make sense to make StructuralNode generic:
```java
public interface StructuralNode<T> extends ContentNode {
    List<T> getBlocks();
}
```
A DescriptionList would become a `StructuralNode<DescriptionListEntry>`, so that the types should match again. (It remains to be seen how this makes extensions look like that iterate the AST when they always have to match on the type parameter of the StructuralNode in addition)
This would pull the trigger for AsciidoctorJ 3.0.0, which we could certainly do.

---
OK, what can we do without a new major version that breaks the API and without changing the semantics of currently working! functions?

I think we could create a bugfix by making `DescriptionList.getBlocks()` return the unmodifiable list of all list entry descriptions.
That would mean that @wilkinsona's original Treeprocessor that exposed this behaviour would 
work again.
But it would miss the list terms. 
On first thought this is tolerable as a Treeprocessor could add a dedicated handling of DescriptionLists that iterates `DescriptionList.getItems()`.

Another restriction would be that the list returned from `DescriptionList.getBlocks()` would become unmodifiable and that items could not be added to this list.
This would be in contrast to the other examples where for example adding a block to a section is done by simply adding a new block to the list returned from `Section.getBlocks()`.
But for DescriptionLists this doesn't work right now anyway, so I guess we could live with this restriction.

@mojavelinux Wdyt?

P.S. We also missed a method in the Processor API to create a DescriptionListEntry, I have a working prototype for this locally now.

**Comment by mojavelinux** [comment]
The description list has a quirky API for reasons that no longer make any sense. Since the purpose of the AsciidoctorJ API is to provide a clean interface to the model, I don't think it's a good idea to cemet this quirkiness. Instead, it would be better to abstract it away so that the user of the API does not have to be aware of these quirks. So I vote against making the type in the getBlocks return value generic. The blocks of a DescriptionList should be StructuralNodes. I'm not sure yet how to do that without changing core, but I'd like it to be a goal.

Specifically, the getBlocks() method on a DescriptionList should return the blocks of the description, if any. There should be separate methods for getTerm() and getDescription(), which would return the text to the left and right of the term delimiter. (Possibly the first entry of getBlocks() would be the primary description, but I'm not committed to that idea).

**Comment by robertpanzer** [comment]
I see.
For me it would make sense to have the DescriptionListEntry represent the `description` ListItem, i.e. the second value in he array and make the `term` ListItems a property of the DescriptionListEntry.

However the parser currently seems to produce ASTs that have the second field in that array `nil`.

I might need some more time thinking about how to get this working without a change in core.
